// Datas comemorativas e campanhas de saúde, com base no Calendário de Saúde
// do Ministério da Saúde (gov.br/saude). Só entram aqui datas fixas (DD/MM) —
// datas móveis do calendário oficial (ex.: "2ª segunda-feira de fevereiro",
// "último domingo do mês") foram deixadas de fora porque exigiriam cálculo de
// data por ano; campanhas de mês inteiro (ex.: Outubro Rosa) entram no dia 1
// do mês correspondente.
//
// Formato de `data`: 'MM-DD'.
export const DATAS_SAUDE = [
  { data: '01-01', tema: 'Janeiro Roxo — Combate à Hanseníase' },
  { data: '01-01', tema: 'Janeiro Branco — Conscientização sobre Saúde Mental' },
  { data: '01-29', tema: 'Dia Nacional da Visibilidade Trans' },
  { data: '01-30', tema: 'Dia Mundial das Doenças Tropicais Negligenciadas' },

  { data: '02-01', tema: 'Semana Nacional de Prevenção da Gravidez na Adolescência' },
  { data: '02-04', tema: 'Dia Mundial do Câncer' },
  { data: '02-13', tema: 'Dia Internacional do Preservativo' },
  { data: '02-15', tema: 'Dia Internacional de Luta contra o Câncer Infantil' },
  { data: '02-18', tema: 'Dia Nacional da Criança Traqueostomizada' },
  { data: '02-20', tema: 'Dia Nacional de Combate às Drogas e ao Alcoolismo' },

  { data: '03-03', tema: 'Dia Mundial da Audição' },
  { data: '03-04', tema: 'Dia Internacional de Conscientização sobre HPV' },
  { data: '03-04', tema: 'Dia Mundial da Obesidade' },
  { data: '03-10', tema: 'Semana Mundial do Glaucoma' },
  { data: '03-13', tema: 'Dia Nacional de Luta contra a Endometriose' },
  { data: '03-15', tema: 'Dia Mundial de Conscientização sobre a Covid Longa' },
  { data: '03-20', tema: 'Dia Mundial da Saúde Bucal' },
  { data: '03-21', tema: 'Dia Mundial da Síndrome de Down' },
  { data: '03-22', tema: 'Dia Mundial da Água' },
  { data: '03-23', tema: 'Dia Nacional de Combate ao HTLV' },
  { data: '03-24', tema: 'Dia Mundial de Combate à Tuberculose' },
  { data: '03-26', tema: 'Dia Mundial de Conscientização da Epilepsia' },
  { data: '03-26', tema: 'Dia Mundial do Câncer de Colo de Útero' },
  { data: '03-27', tema: 'Dia Nacional de Combate ao Câncer Colorretal' },
  { data: '03-30', tema: 'Dia Mundial do Transtorno Bipolar' },

  { data: '04-01', tema: 'Abril pela Segurança do Paciente' },
  { data: '04-02', tema: 'Dia Mundial da Conscientização sobre o Autismo' },
  { data: '04-04', tema: 'Dia Nacional do Portador da Doença de Parkinson' },
  { data: '04-07', tema: 'Dia Mundial da Saúde' },
  { data: '04-08', tema: 'Dia Mundial de Luta Contra o Câncer' },
  { data: '04-11', tema: 'Dia Mundial de Conscientização da Doença de Parkinson' },
  { data: '04-14', tema: 'Dia Mundial da Doença de Chagas' },
  { data: '04-17', tema: 'Dia Internacional da Hemofilia' },
  { data: '04-24', tema: 'Semana Mundial da Imunização' },
  { data: '04-25', tema: 'Dia Mundial de Luta contra a Malária' },
  { data: '04-26', tema: 'Dia Nacional de Prevenção e Combate à Hipertensão Arterial' },
  { data: '04-28', tema: 'Dia Nacional de Conscientização sobre a Doença de Fabry' },

  { data: '05-07', tema: 'Dia Internacional de Luta contra a Endometriose' },
  { data: '05-08', tema: 'Dia da Talassemia' },
  { data: '05-08', tema: 'Dia Mundial do Câncer de Ovário' },
  { data: '05-10', tema: 'Dia Mundial do Lúpus' },
  { data: '05-12', tema: 'Dia de Conscientização da Fibromialgia e Fadiga Crônica' },
  { data: '05-16', tema: 'Dia Mundial de Conscientização sobre a Doença Celíaca' },
  { data: '05-17', tema: 'Dia Mundial da Hipertensão Arterial' },
  { data: '05-18', tema: 'Dia de Conscientização sobre a Vacina Contra HIV/Aids' },
  { data: '05-19', tema: 'Dia Nacional de Doação do Leite Humano' },
  { data: '05-19', tema: 'Dia Nacional de Combate à Cefaleia' },
  { data: '05-24', tema: 'Dia Nacional de Conscientização sobre a Esquizofrenia' },
  { data: '05-25', tema: 'Dia Internacional da Tireoide' },
  { data: '05-26', tema: 'Dia Nacional de Combate ao Glaucoma' },
  { data: '05-28', tema: 'Dia Internacional de Ação pela Saúde da Mulher' },
  { data: '05-30', tema: 'Dia Mundial da Esclerose Múltipla' },
  { data: '05-31', tema: 'Dia Mundial Sem Tabaco' },

  { data: '06-01', tema: 'Junho Vermelho — Incentivo à Doação de Sangue' },
  { data: '06-02', tema: 'Dia Mundial de Conscientização dos Transtornos Alimentares' },
  { data: '06-03', tema: 'Dia de Conscientização contra a Obesidade Infantil' },
  { data: '06-06', tema: 'Dia Nacional do Teste do Pezinho' },
  { data: '06-09', tema: 'Dia da Imunização' },
  { data: '06-13', tema: 'Dia Global de Conscientização sobre o Câncer de Pele Não Melanoma' },
  { data: '06-14', tema: 'Dia Mundial do Doador de Sangue' },
  { data: '06-18', tema: 'Dia Mundial de Conscientização sobre o Câncer de Rim' },
  { data: '06-19', tema: 'Dia Mundial de Conscientização sobre a Doença Falciforme' },
  { data: '06-21', tema: 'Dia Nacional de Controle da Asma' },
  { data: '06-24', tema: 'Dia Nacional de Conscientização sobre a Fissura Labiopalatina' },
  { data: '06-26', tema: 'Dia Nacional do Diabetes' },
  { data: '06-29', tema: 'Semana Mundial da Alergia' },

  { data: '07-01', tema: 'Julho Amarelo — Combate às Hepatites Virais' },
  { data: '07-01', tema: 'Dia da Vacina BCG' },
  { data: '07-09', tema: 'Dia Nacional de Alerta à Insuficiência Cardíaca' },
  { data: '07-10', tema: 'Dia da Saúde Ocular' },
  { data: '07-27', tema: 'Dia Mundial do Câncer de Cabeça e Pescoço' },
  { data: '07-28', tema: 'Dia Mundial de Luta Contra as Hepatites Virais' },

  { data: '08-01', tema: 'Agosto Dourado — Promoção do Aleitamento Materno' },
  { data: '08-01', tema: 'Dia Mundial de Combate ao Câncer de Pulmão' },
  { data: '08-05', tema: 'Dia Nacional da Saúde' },
  { data: '08-08', tema: 'Dia Nacional de Prevenção e Controle do Colesterol' },
  { data: '08-08', tema: 'Dia Nacional da Pessoa com Atrofia Muscular Espinhal' },
  { data: '08-10', tema: 'Semana Nacional de Controle e Combate à Leishmaniose' },
  { data: '08-20', tema: 'Dia Mundial Contra os Mosquitos' },
  { data: '08-21', tema: 'Semana Nacional da Pessoa com Deficiência Intelectual e Múltipla' },
  { data: '08-29', tema: 'Dia Nacional de Combate ao Fumo' },
  { data: '08-30', tema: 'Dia Nacional de Conscientização sobre a Esclerose Múltipla' },

  { data: '09-01', tema: 'Setembro Verde — Conscientização sobre Doação de Órgãos' },
  { data: '09-01', tema: 'Setembro Dourado — Conscientização sobre o Câncer Infanto-Juvenil' },
  { data: '09-04', tema: 'Dia Mundial da Saúde Sexual' },
  { data: '09-05', tema: 'Dia Nacional de Conscientização sobre a Fibrose Cística' },
  { data: '09-10', tema: 'Dia Mundial de Prevenção ao Suicídio' },
  { data: '09-15', tema: 'Dia Mundial de Conscientização sobre Linfomas' },
  { data: '09-16', tema: 'Dia Nacional de Combate e Prevenção à Trombose' },
  { data: '09-17', tema: 'Dia Mundial da Segurança do Paciente' },
  { data: '09-19', tema: 'Aniversário do Sistema Único de Saúde (SUS)' },
  { data: '09-21', tema: 'Dia Mundial da Doença de Alzheimer' },
  { data: '09-22', tema: 'Dia Nacional da Saúde de Adolescentes e Jovens' },
  { data: '09-27', tema: 'Dia Nacional de Doação de Órgãos' },

  { data: '10-01', tema: 'Outubro Rosa — Conscientização sobre o Câncer de Mama' },
  { data: '10-01', tema: 'Mês de Conscientização sobre a Dislexia' },
  { data: '10-05', tema: 'Dia Mundial de Combate à Meningite' },
  { data: '10-06', tema: 'Dia Mundial da Paralisia Cerebral' },
  { data: '10-10', tema: 'Dia Mundial da Saúde Mental' },
  { data: '10-11', tema: 'Dia Nacional de Prevenção da Obesidade' },
  { data: '10-13', tema: 'Dia Mundial da Trombose' },
  { data: '10-17', tema: 'Dia Nacional da Vacinação' },
  { data: '10-19', tema: 'Dia Mundial de Combate ao Câncer de Mama' },
  { data: '10-20', tema: 'Dia Mundial e Nacional da Osteoporose' },
  { data: '10-24', tema: 'Dia Mundial de Combate à Poliomielite' },
  { data: '10-25', tema: 'Dia Nacional da Saúde Bucal' },
  { data: '10-29', tema: 'Dia Mundial do Acidente Vascular Cerebral (AVC)' },
  { data: '10-30', tema: 'Dia Nacional de Luta do Paciente Reumático' },

  { data: '11-01', tema: 'Novembro Azul — Conscientização sobre o Câncer de Próstata e a Saúde do Homem' },
  { data: '11-01', tema: 'Semana Nacional de Prevenção do Câncer Bucal' },
  { data: '11-03', tema: 'Dia Mundial e Nacional da Saúde Única' },
  { data: '11-10', tema: 'Dia Mundial do HTLV' },
  { data: '11-12', tema: 'Dia Mundial da Pneumonia' },
  { data: '11-12', tema: 'Dia Nacional de Prevenção das Arritmias Cardíacas e Morte Súbita' },
  { data: '11-16', tema: 'Dia Nacional de Atenção à Dislexia' },
  { data: '11-17', tema: 'Dia Nacional de Combate ao Câncer de Próstata' },
  { data: '11-17', tema: 'Dia Mundial da Prematuridade' },
  { data: '11-23', tema: 'Dia Nacional de Combate ao Câncer Infantil' },
  { data: '11-25', tema: 'Dia Nacional do Doador Voluntário de Sangue' },
  { data: '11-27', tema: 'Dia Nacional de Luta contra o Câncer de Mama' },

  { data: '12-01', tema: 'Dezembro Vermelho — Prevenção ao HIV/Aids' },
  { data: '12-01', tema: 'Dezembro Laranja — Conscientização sobre o Câncer de Pele' },
  { data: '12-01', tema: 'Dia Mundial de Luta Contra a Aids' },
  { data: '12-02', tema: 'Dia Pan-Americano de Saúde' },
  { data: '12-03', tema: 'Dia Internacional de Luta das Pessoas com Deficiência' },
  { data: '12-06', tema: 'Dia Nacional de Mobilização dos Homens pelo Fim da Violência contra Mulheres' },
  { data: '12-14', tema: 'Semana de Mobilização Nacional para Doação de Medula Óssea' },
];
